services:
  keycloak_business:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME_ADMIN_URL: https://localhost:8443
      KC_HOSTNAME_URL: https://localhost:8443
    depends_on:
      keycloak_postgres:
        condition: service_healthy
    networks:
      - keycloak_nginx_dev_network

  keycloak_postgres:
    image: postgres:15-alpine
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_nginx:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_nginx_dev_network
  keycloak-nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - keycloak_business
    networks:
      - keycloak_nginx_dev_network

volumes:
  pgdata_keycloak_nginx:
networks:
  keycloak_nginx_dev_network:
    driver: bridge